# Generated by Django 5.2.6 on 2026-01-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singboxuser',
            old_name='enabled',
            new_name='active',
        ),
    ]
